### ISSUE TITLE
Installation failure: no settings options

### ISSUE THREAD

**Issue by StefGuad** [hendrikhoffmann/ioBroker.cloudrain#173]
With pleasure I found this adapter today, however the installation does not seem to work for me.
I have no settings options in the instance afterwards.

Can anyone help?

![2023-04-11_21h26_19](https://user-images.githubusercontent.com/76149512/231268914-c5de3096-ca37-4991-8b15-c0130bf64465.png)

**Comment by StefGuad** [comment]
Hallo,
ich habe die Instanz nun mehrmals entfernt und wieder hinzugefügt, aber mir werden einfach keine Einstellungsoptionen angezeigt, wenn ich auf den Schraubenschlüssel klicke.
Das Hinzufügen des Adapters hat das ausgegeben
<img width="371" alt="2023-06-04_16h29_19" src="https://github.com/hendrikhoffmann/ioBroker.cloudrain/assets/76149512/caefa5e6-7ffe-4789-9d7a-71332106cf55">

**Comment by hendrikhoffmann** [comment]
Hallo,
könnte sein das das irgendwas inkompatibel mit deiner installierten ioBroker Version ist.

Kannst du mal folgendes probieren:
Im Browser (idealerweise Chrome) F12 drücken und dann in den sich öffnenden Dev-Tools das Tab "Console" auswählen.
Jetzt auf den Schraubenschlüssel der cloudrain Instanz klicken.
In dem Log sollten Fehlermeldungen ausgegeben werden.
Bitte davon einen Screenshot,

**Comment by StefGuad** [comment]
Hallo,
hier der Screenshot

[image: image.png]


Mein System aktuell:
JS-Controller: 4.0.24
node.js 16.20.0

Habe gerade ein Update auf node v18.16.0 gemacht, aber leider dasselbe.

Was könnte ich sonst noch machen?

Danke,
Stefan


Am So., 4. Juni 2023 um 17:20 Uhr schrieb hendrikhoffmann <
***@***.***>:

**Comment by hendrikhoffmann** [comment]
Ich habe mir gerade die aktuelle ioBroker Version installiert, kann das Problem nachvollziehen und melde mich wenn ich eine Lösung habe. Sollte nur eine Kleinigkeit sein.

**Comment by StefGuad** [comment]
Super, besten Dank.
Sei so gut und melde dich, sobald es laufen sollte, freu mich schon drauf!

Grüße aus Südtirol,
Stefan

Am Mo., 5. Juni 2023 um 19:49 Uhr schrieb hendrikhoffmann <
***@***.***>:

**Comment by Netfreak25** [comment]
Hallo, dann melde ich mich doch auch mal zu Wort. Ich dachte eigentlich es würde nicht mehr weiterentwickelt werden. Und wollte den Tip da lassen das man die Benutzerdaten im Code hinterlegen kann Notfalls - damit läuft es bei mir seit vorgestern sauber ;) -> Hiervon rate ich aber explizit ab, Benutzerdaten sollte man nicht im klartext speichern, zudem dürfte ein update die Änderungen verwerfen

Sobald das Update draussen ist werde ich es allerdings nochmal versuchen und feedback geben!

LG,
Moritz aus FFM

**Comment by hendrikhoffmann** [comment]
.. und ich dachte das keiner außer mir den Adapter nutzt, deswegen habe ich ihn nicht gepatcht :)

Der Bug ist gefixt und die hochgeladene Version 0.2.7 läuft bei mir.
Eigentlich sollte sich das npm Paket automatisch updaten und dann installierbar sein.
Wenn das bis Morgen nicht passiert ist schau ich nochmal rein.

**Comment by hendrikhoffmann** [comment]
Ich habe den Adapter gerade nochmal in einer frischen Installation getestet. Funktioniert nach Installation über die GUI wie im Readme.md beschrieben und kann von euch genutzt werden.
Bis das npm Release die Version hochzählt kann es noch ein paar Tage dauern. 
Da steht super spannendes Refactoring an. Mach ich sobald das Wetter schlechter ist.

**Comment by hendrikhoffmann** [comment]
Um die Zustände zu speichern einfach den Adapter History installieren und dann im Objektbaum bei allen gewünschten Werten die Speicherung aktivieren (Zahnrad hinten beim Wert).
Zur Visualisierung in Diagrammen verwende ich den Adapter ECharts, gibt aber auch andere.

**Comment by hendrikhoffmann** [comment]
Bug fixed.
